window.Shopify = {
  theme_settings: {
    display_tos_checkbox: false,
    go_to_checkout: true,
    cart_action: 'ajax',
    cart_shipping_calculator: false,
    collection_swatches: false,
    collection_secondary_image: true,
    display_inventory_left: false,
    inventory_threshold: 10,
    limit_quantity: false,
    menu_position: 'inline',
    newsletter_popup: false,
    newsletter_popup_days: '7',
    newsletter_popup_mobile: false,
    newsletter_popup_seconds: 8,
    pagination_type: 'infinite_scroll',
    search_pagination_type: 'basic_pagination',
    enable_shopify_review_comments: true,
    enable_shopify_collection_badges: true,
    quick_shop_thumbnail_position: 'bottom-thumbnails',
    product_form_style: 'swatches',
    sale_banner_enabled: true,
    display_savings: true,
    display_sold_out_price: true,
    sold_out_text: 'Sold Out',
    free_text: 'Free',
    video_looping: false,
    quick_shop_style: 'inline',
    hover_enabled: false,
    image_loading_style: 'blur-up',
    search_option: 'product,page,article',
    search_items_to_display: 4,
    enable_autocomplete: true,
    page_dots_enabled: false,
    slideshow_arrow_size: 'light',
    quick_shop_enabled: false,
  },
  routes: {
    cart_url: '/cart',
    root_url: '/',
    search_url: '/search',
  },
  translation: {
    agree_to_terms_warning:
      'You must agree with the terms and conditions to checkout.',
    one_item_left: 'item left',
    items_left_text: 'items left',
    cart_savings_text: 'Total Savings',
    cart_discount_text: 'Discount',
    cart_subtotal_text: 'Subtotal',
    cart_remove_text: 'Remove',
    cart_free_text: 'Free',
    newsletter_success_text: 'Thank you for joining our mailing list!',
    notify_email: 'Enter your email address...',
    notify_email_value: 'translation missing: en.contact.fields.email',
    notify_email_send: 'Send',
    notify_message_first: 'Please notify me when ',
    notify_message_last: ' becomes available - ',
    notify_success_text:
      'Thanks! We will notify you when this product becomes available!',
    add_to_cart: 'Add to Cart',
    coming_soon_text: 'Coming Soon',
    sold_out_text: 'Sold Out',
    sale_text: 'Sale',
    savings_text: 'You Save',
    from_text: 'from',
    new_text: 'New',
    pre_order_text: 'Pre-Order',
    unavailable_text: 'Unavailable',
    all_results: 'View all results',
    no_results: 'Sorry, no results!',
  },
  media_queries: {
    small: {},
    medium: {},
    large: {},
    larger: {},
    xlarge: {},
    ie10: {},
    tablet: {},
  },
  shop: 'remi-club.myshopify.com',
  locale: 'en',
  currency: {
    active: 'USD',
    rate: '1.0',
  },
  country: 'US',
  theme: {
    name: 'Side CART Cus Dev 5-13-22',
    id: 132512481493,
    theme_store_id: null,
    role: 'main',
    handle: 'null',
    style: {
      id: null,
      handle: null,
    },
  },
  cdnHost: 'cdn.shopify.com',
  queryParams: {},
  money_format: '$',
  Image: {},
  modules: true,
  recaptchaV3: {
    siteKey: '6LcCR2cUAAAAANS1Gpq_mDIJ2pQuJphsSQaUEuc9',
  },
  PaymentButton: {},
  trackingConsent: {},
  customerPrivacy: {},
};
